[project]
name = "workflow"
version = "1.2.1"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "Luis Fernando Umaña Castro", email = "luis.umanacastro@ucr.ac.cr" },
]
classifiers = ["Development Status :: 2 - Pre-Alpha"]
dependencies = ["appdirs", "bibtexparser", "click", "pyyaml"]

[project.scripts]
workflow = "main:cli"
bib2yaml = "prismar.bib2yaml:cli"
cleta = "lectkit.cleta:cli"
crete = "lectkit.crete:cli"
inittex = "itep.create:cli"
relink = "itep.links:cli"
mergebib = "prismar.mergebib:cli"
nofi = "lectkit.nofi:cli"
nori = "prismar.nori:cli"
prisma-import-bib = "prismar.prismaimportbib:cli"
prisma-review = "prismar.prismareview:cli"

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = "."
