# Generated by Django 5.0.2 on 2024-06-05 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('methods_synthesis', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('results_synthesis', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=200)),
                ('alias', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_author', models.CharField(choices=[('author', 'author'), ('bookauthor', 'bookauthor'), ('editor', 'editor'), ('afterword', 'afterword'), ('annotator', 'annotator'), ('commentator', 'commentator'), ('forward', 'forward'), ('introduction', 'introduction'), ('translator', 'translator'), ('holder', 'holder')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Bib_author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_author', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bib_entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bibkey', models.CharField(blank=True, max_length=200, null=True)),
                ('accessed', models.DateField(blank=True, db_comment='', null=True)),
                ('institution', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('organization', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('indextitle', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('booktitle', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('maintitle', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('journaltitle', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('issuetitle', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('eventtitle', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('reprinttitle', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('series', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('issue_volume', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_number', models.CharField(blank=True, max_length=20, null=True)),
                ('part', models.CharField(blank=True, db_comment='', max_length=20, null=True)),
                ('issue', models.CharField(blank=True, db_comment='', max_length=20, null=True)),
                ('volumes', models.CharField(blank=True, db_comment='', max_length=20, null=True)),
                ('edition', models.PositiveSmallIntegerField(blank=True, db_comment='', null=True)),
                ('version', models.CharField(blank=True, db_comment='', max_length=50, null=True)),
                ('pubstate', models.CharField(blank=True, db_comment='', max_length=100, null=True)),
                ('pages', models.CharField(blank=True, max_length=20, null=True)),
                ('pagetotal', models.CharField(blank=True, db_comment='', max_length=20, null=True)),
                ('pagination', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('publication_date', models.DateField(blank=True, db_comment='', null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.SmallIntegerField(blank=True, db_comment='', null=True)),
                ('eventdate', models.DateField(blank=True, db_comment='', null=True)),
                ('urldate', models.DateField(blank=True, db_comment='', null=True)),
                ('location', models.CharField(blank=True, db_comment='', max_length=100, null=True)),
                ('venue', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('doi', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('eid', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('eprint', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('eprinttype', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('addendum', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('notes', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('howpublished', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('language', models.CharField(blank=True, db_comment='', max_length=200, null=True)),
                ('isn', models.CharField(blank=True, max_length=200, null=True)),
                ('abstract_text', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('annotation', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('file_path', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('library', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('label', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('shorthand', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
                ('shorthandintro', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('execute_task', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('keywords', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('options', models.TextField(blank=True, db_comment='', max_length=21844, null=True)),
                ('ids', models.CharField(blank=True, db_comment='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Isn_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_isn', models.CharField(choices=[('isan', 'isan'), ('isbn', 'isbn'), ('ismn', 'ismn'), ('isrn', 'isrn'), ('issn', 'issn'), ('iswc', 'iswc')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_list', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rationale_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale_argument', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referenced_databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('proxy', models.CharField(blank=True, max_length=400, null=True)),
                ('aliases', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review_rationale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieved', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('included', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('include_rationale', models.TextField(blank=True, max_length=21844, null=True)),
                ('reatrive_rationale', models.TextField(blank=True, max_length=21844, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Url_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_string', models.CharField(max_length=500)),
                ('main_url', models.BooleanField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author_entry'),
        ),
        migrations.AddField(
            model_name='bib_author',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.author_type'),
        ),
        migrations.AddField(
            model_name='bib_author',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.author'),
        ),
        migrations.AddField(
            model_name='bib_entries',
            name='references',
            field=models.ManyToManyField(blank=True, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='bib_author',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='article_tags',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='bib_entries',
            name='isn_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prismadb.isn_list'),
        ),
        migrations.AddField(
            model_name='review_rationale',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='review_rationale',
            name='id_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.keyword'),
        ),
        migrations.AddField(
            model_name='review_rationale',
            name='id_rationale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.rationale_list'),
        ),
        migrations.AddField(
            model_name='reviewed',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='reviewed',
            name='id_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.keyword'),
        ),
        migrations.AddField(
            model_name='article_tags',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.tags'),
        ),
        migrations.AddField(
            model_name='url_list',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries'),
        ),
        migrations.AddField(
            model_name='url_list',
            name='id_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.referenced_databases'),
        ),
        migrations.AddConstraint(
            model_name='bib_author',
            constraint=models.UniqueConstraint(fields=('id_author', 'id_article', 'category'), name='unique_author_function_per_article'),
        ),
        migrations.AddConstraint(
            model_name='bib_entries',
            constraint=models.UniqueConstraint(fields=('title', 'year', 'issue_volume'), name='unique_bib_entry'),
        ),
        migrations.AddConstraint(
            model_name='review_rationale',
            constraint=models.UniqueConstraint(fields=('id_key', 'id_article', 'id_rationale'), name='dont_repit_rationale_per_article_per_keyword'),
        ),
        migrations.AddConstraint(
            model_name='reviewed',
            constraint=models.UniqueConstraint(fields=('id_key', 'id_article'), name='unique_review_per_article_per_keyword'),
        ),
        migrations.AddConstraint(
            model_name='article_tags',
            constraint=models.UniqueConstraint(fields=('id_tag', 'id_article'), name='dont_repit_tags_per_article'),
        ),
        migrations.AddConstraint(
            model_name='url_list',
            constraint=models.UniqueConstraint(fields=('id_article', 'id_database'), name='unique_url_per_database'),
        ),
    ]
