# Generated by Django 5.0.2 on 2024-09-03 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismadb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article_tags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_tags',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bib_entries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bib_entries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rationale_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rationale_list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Prisma2020Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(help_text='Abstract of the systematic review or meta-analysis.')),
                ('registration', models.CharField(blank=True, help_text='Registration details (PROSPERO registration number).', max_length=200, null=True)),
                ('information_sources', models.TextField(help_text='Information sources used in the review (databases, registries).')),
                ('search_strategy', models.TextField(help_text='Search strategy details.')),
                ('selection_process', models.TextField(help_text='Process for selecting studies (screening and inclusion).')),
                ('data_collection_process', models.TextField(help_text='Process for data collection (data extraction methods).')),
                ('data_items', models.TextField(help_text='List of all variables for which data were sought (PICO elements).')),
                ('study_risk_of_bias_assessment', models.TextField(help_text='Methods for assessing risk of bias in the included studies.')),
                ('effect_measures', models.TextField(help_text='Effect measures (risk ratios, mean differences).')),
                ('synthesis_methods', models.TextField(help_text='Methods used to synthesize results.')),
                ('reporting_bias_assessment', models.TextField(help_text='Methods used to assess reporting biases.')),
                ('certainty_assessment', models.TextField(help_text='Methods for assessing the certainty of the body of evidence.')),
                ('results_study_selection', models.TextField(help_text='Results of the study selection process (e.g., PRISMA flow diagram).')),
                ('results_study_characteristics', models.TextField(help_text='Characteristics of the included studies.')),
                ('results_risk_of_bias_in_studies', models.TextField(help_text='Risk of bias in the included studies.')),
                ('results_synthesis', models.TextField(help_text='Synthesis of the results (e.g., meta-analysis).')),
                ('results_reporting_biases', models.TextField(help_text='Results of the assessment of reporting biases.')),
                ('results_certainty_of_evidence', models.TextField(help_text='Certainty of the evidence (e.g., GRADE).')),
                ('discussion_summary_of_evidence', models.TextField(help_text='Summary of the main findings.')),
                ('discussion_limitations', models.TextField(help_text='Limitations of the evidence and the review process.')),
                ('discussion_conclusions', models.TextField(help_text='General interpretation of the results.')),
                ('funding', models.TextField(help_text='Details of funding sources and conflicts of interest.')),
                ('accessibility_of_data', models.TextField(help_text='Accessibility of data, code, and other resources.')),
                ('acknowledgements', models.TextField(help_text='Acknowledgements (e.g., contributors, peer reviewers).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prismadb.bib_entries')),
            ],
            options={
                'verbose_name': 'PRISMA 2020 Checklist',
                'verbose_name_plural': 'PRISMA 2020 Checklists',
            },
        ),
    ]
