# Generated by Django 5.0.2 on 2024-09-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prismadb', '0002_abstract_created_at_abstract_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bib_entries',
            name='accessed',
        ),
    ]
