# Generated by Django 5.0.2 on 2024-09-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismadb', '0003_remove_bib_entries_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='background',
            field=models.TextField(blank=True, db_comment='', max_length=21844, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='discussion_conclussion',
            field=models.TextField(blank=True, db_comment='', max_length=21844, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='information_sources',
            field=models.TextField(blank=True, db_comment='', max_length=21844, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='registration',
            field=models.TextField(blank=True, db_comment='', max_length=21844, null=True),
        ),
    ]
