# Generated by Django 5.0.2 on 2024-09-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prismadb', '0004_abstract_background_abstract_discussion_conclussion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstract',
            old_name='discussion_conclussion',
            new_name='discussion_conclusion',
        ),
    ]
